name: "syrlex2mqtt"
description: "syrlex2mqtt simulates the SyrConnect cloud and makes the SYR water softening units of the LEX Plus series available via MQTT"
version: "0.2.1"
slug: "syrlex2mqtt"
init: false
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: http server port
  443/tcp: https server port
services:
  - mqtt:need
options:
  verbose_logging: false
  additional_properties: ""
schema:
  verbose_logging: bool
  additional_properties: "str?"
